[package]
name = "zero-meet"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
iroh.workspace = true
iroh-moq.workspace = true
web-transport-iroh.workspace = true
irpc.workspace = true
irpc-iroh.workspace = true
iroh-tickets.workspace = true
moq-net.workspace = true
postcard.workspace = true
rand.workspace = true
serde.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
tempfile = "3"
