[workspace]
members = ["meet", "app"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["rt"] }
tracing = "0.1"
moq-net = "=0.2.20"
moq-native = { version = "=0.19.17", default-features = false, features = ["websocket", "aws-lc-rs"] }
iroh = { version = "=1.2.0", default-features = false, features = ["portmapper", "tls-aws-lc-rs"] }
iroh-moq = { git = "https://github.com/n0-computer/iroh-live", rev = "de7f43bfc466988f08b7e63acdd7fb295a9f9fd2" }
web-transport-iroh = "=0.7.0"
irpc = "=0.17.0"
irpc-iroh = "=0.17.0"
iroh-tickets = "=1.0.0"
postcard = { version = "1", features = ["alloc"] }
rand = "0.9"

[patch.crates-io]
moq-net = { git = "https://github.com/Frando/moq", rev = "253441fdb49b0d5606d4bdee54e4571478269a08" }
moq-native = { git = "https://github.com/Frando/moq", rev = "253441fdb49b0d5606d4bdee54e4571478269a08" }

[profile.dev]
debug = 1

[profile.release]
strip = true
lto = "thin"
