services:
  server:
    build:
      context: .
      dockerfile: docker/build.Dockerfile
    restart: unless-stopped
    stop_grace_period: 15s
    volumes:
      - server-data:/data

volumes:
  server-data:
